### ISSUE TITLE
BMIS v2

### ISSUE THREAD

**Issue by nathaniel01997** [rhalp10/BMIS-v2#4]
hello po tanong lng po bakit di po maka login pumapasok sya sa else agad?

**Comment by rhalp10** [comment]
> hello po tanong lng po bakit di po maka login pumapasok sya sa else agad?

not sure,  later icheck ko kung bakit hindi. unmaintained na kasi to nakalimutan ko na irevise eh..

**Comment by rhalp10** [comment]
sorry old system na to walang explanation or details kung ano ung mga acc.

sa first if statement kase i che-check niyan, if yung input box sa
login form ay empty..

----------------------------
*if (empty($_POST['username']) || empty($_POST['password'])) *

kung ang input box ba ng username (*$_POST['username']*) ay walang laman ?
walang laman "*TRUE*"
kung ang input box ba ng password (*$_POST['* *password  ']*) ay walang
laman ?  walang laman   " *TRUE  *"

----------------------------
dahil same silang true at walanag naman.. ang ieexecute lang sa if else ,
ay IF.

*EXECUTE *
if (true || true){
 echo alert();
}
*SKIP*
else{

}

---------------------------- ----------------------------
----------------------------
bagong senario naman tayo, paano kung may laman na lahat ng input box sa
login form?

----------------------------
*if (empty($_POST['username']) || empty($_POST['password'])) *

kung ang input box ba ng username (*$_POST['username']*) ay walang laman
?may laman "*FALSE*"
kung ang input box ba ng password (*$_POST['* *password  ']*) ay walang
laman ?  may laman   " *FALSE  *"

----------------------------
Dahil parehong "*FALSE", *iiSkip na niya yung IF statement at ang last na
maari niyang gawin ay

if (false || false ){
 echo alert();
}
*EXECUTE si ELSE*
else{

}

----------------------------
user:  secretary1
pass:secretary
